version: 1.0.{build}
os: Visual Studio 2017
test: off
clone_folder: C:\projects\fish_deformation
branches:
  only:
    - master
install:
  - git submodule update --init --recursive
  - cinstall: python
build_script:
  - echo Running cmake...
  - cd c:\projects\fish_deformation
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -T "host=x64" ..
  - msbuild %MSBuildOptions% fish_deformation
